baseurl = "https://bookmarks.hibariya.org"
languageCode = "en"
title = "TL;DR Bookmarks"
theme = "kiss"
copyright = "(c) <a href=\"https://hibariya.org/\">Hibariya Lerche</a> 2018"
# disqusShortname = "shortname"
googleAnalytics = "UA-64572851-4"
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Hibariya Lerche" # Site author's full name
#authorEmail = "ribice@gmail.com"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "hibariya"
github = "hibariya"
#email = "ribice@gmail.com"
#linkedin = "ribice"
#gitlab = "ribice"
#instagram = ""
#codepen = ""
#facebook = ""

[params.social.config]
platforms = ["twitter","github","email","email","linkedin","gitlab"]

#[params.matomoAnalytics]
#siteID = 1
#rootURL = "//matomo.example.com/"

#[params.fathomAnalytics]
#rootURL = "//fathom.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

